"""Add trips table

Revision ID: a5cf80d88ea4
Revises: 5f8d6baedd52
Create Date: 2025-09-16 14:28:46.412637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cf80d88ea4'
down_revision: Union[str, Sequence[str], None] = '5f8d6baedd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('seats_left', sa.Integer(), nullable=False),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seats_left >= 0', name=op.f('ck_trips_ck_seats_left_nonnegative')),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_trips_bus_id_buses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=True)
    op.create_index(op.f('ix_trips_name'), 'trips', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_name'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
