"""Add buses table

Revision ID: 5f8d6baedd52
Revises: 62f6dc0682cf
Create Date: 2025-09-10 07:28:07.499082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8d6baedd52'
down_revision: Union[str, Sequence[str], None] = '62f6dc0682cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('seats_quantity', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=10), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seats_quantity >= 0', name=op.f('ck_buses_ck_seats_quantity_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buses')),
    sa.UniqueConstraint('number_plate', name=op.f('uq_buses_number_plate'))
    )
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
